/**:
    ros__parameters:
      app_name: "IVAQ Finder"
      app_id: "157194"
      app_key: "277ef255ddab87874f7426fafeb0e2e"
      app_license: "Qae27A6m83ZVyewec1CYok/uBhET8GdDP/V5xkJME/C+gQYwa6abBnJd5ERn99Y+dhGuVKLCkRTqOuXeUk0Pn404fYdRkwClknuOnXLL3SzPvPgmd684W37TvA2W7HdLMTr0WaySlET/OyJQWlxMsyDPR304xIUswaroXj0G45sYWauZ8/kWxZWbDGS0YOAyJxmmeHpB1lmN/DSOS54nRVJ/xjNbpXwtntzD9kRfDotgMOobjs/+mbfN1NwP+jdvGjBFZJykOOAD6PZ3+pS+fR0OWt2sGSifWfKhy4EGHvrXjJCbiLpP0m0U1LFqvpOtG10eMymptDv4rm88PZsNUw=="
      developer_account: "diego.sanchez@ivaq.es"
      baudrate: "230400"

      num_of_initialization_retries: 3

      tf_frame_prefix: ""
      imu_frame: "psdk_imu_link"
      body_frame: "psdk_base_link"
      map_frame: "psdk_map_enu"
      gimbal_base_frame: "psdk_gimbal_base_link"
      gimbal_frame: "psdk_gimbal_link"
      camera_frame: "psdk_camera_link"
      perception_camera_frame: "psdk_perception_camera_link"
      publish_transforms: true

      file_path: "/logs/media/"

      # Mandatory modules to be initialized. Mark with a true those which you
      # consider mandatory for your application, false otherwise. Be aware that
      # some modules might have inter-dependencies. Non mandatory modules will
      # still be initialized but if case of failure, the node will continue to run.
      mandatory_modules:
        telemetry: true
        flight_control: true
        camera: false
        gimbal: false
        liveview: false
        hms: false
        perception: false

      data_frequency: # Options are: 1, 5, 10, 50, 100, 200, 400 Hz
        imu: 10
        attitude: 10
        acceleration: 10
        velocity: 10
        angular_velocity: 10
        position: 10
        altitude: 10
        gps_fused_position: 10
        gps_data: 5
        rtk_data: 5
        magnetometer: 50
        rc_channels_data: 1
        gimbal_data: 1
        flight_status: 1
        battery_level: 1
        control_information: 1
        esc_data_frequency: 1
